"""Build the checked-in benchmark report from measured result artifacts."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def latest(pattern: str):
    paths = sorted(ROOT.glob(pattern))
    return json.loads(paths[-1].read_text(encoding="utf-8")) if paths else None


def latest_for_corpus(pattern: str, paper_count: int):
    for path in reversed(sorted(ROOT.glob(pattern))):
        row = json.loads(path.read_text(encoding="utf-8"))
        if row.get("papers") == paper_count:
            return row
    return None


def value(metrics, key):
    return "—" if key not in metrics else f"{metrics[key]:.3f}"


def main():
    paper_count = len(json.loads((ROOT / "data_manifest.json").read_text(encoding="utf-8")))
    retrieval = {}
    for name in ("bm25", "bm25_field", "bm25_field_qe", "dense_lsa", "hybrid_lsa_rrf", "dense_minilm", "hybrid_rrf", "hybrid_reranker"):
        result = latest_for_corpus(f"results/retrieval/{name}/*/summary.json", paper_count)
        retrieval[name] = result or {"metadata": {"status": "NOT RUN"}}
    gate_off = latest("results/agent/extractive_gate_off.json")
    gate_on = latest("results/agent/extractive_gate_on.json")
    reliability = latest("results/reliability/summary.json")
    citation = latest("results/citation/summary.json")
    performance = latest("results/performance_summary.json")
    measured = next((row for row in retrieval.values() if row.get("papers")), {})
    ablation = {
        "retrieval": {name: row.get("metrics") for name, row in retrieval.items() if row.get("metrics")},
        "evidence_gate": {
            "off": {key: gate_off.get(key) for key in ("target_paper_coverage", "refusal_accuracy", "evidence_grounded_rate_structural")} if gate_off else "NOT RUN",
            "on": {key: gate_on.get(key) for key in ("target_paper_coverage", "refusal_accuracy", "evidence_grounded_rate_structural")} if gate_on else "NOT RUN",
        },
        "verifier": "REQUIRES API KEY",
        "multi_agent_vs_simplified": "REQUIRES API KEY",
    }
    target = ROOT / "results" / "ablation" / "summary.json"; target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(ablation, ensure_ascii=False, indent=2), encoding="utf-8")

    lines = [
        "# Benchmark report", "",
        "All values below are generated by repository scripts. The frozen retrieval labels are assistant-authored diagnostics and have **0 independently human-verified questions**, so these results are not a public benchmark.", "",
        "## Retrieval (paper level)", "",
        f"{measured.get('papers', '—')} papers / {measured.get('chunks', '—')} chunks / "
        f"{measured.get('frozen_questions', '—')} frozen questions "
        f"({measured.get('evaluated_questions', '—')} answerable questions evaluated).", "",
        "| Method | Status | Hit@1 | Recall@3 | MRR | Mean latency |", "|---|---|---:|---:|---:|---:|",
    ]
    labels = {"bm25":"BM25", "bm25_field":"BM25 + title prior", "bm25_field_qe":"BM25 + title prior + query expansion", "dense_lsa":"Dense LSA (offline baseline)", "hybrid_lsa_rrf":"BM25 + Dense LSA (RRF)", "dense_minilm":"Sentence-Transformer dense", "hybrid_rrf":"BM25 + Sentence-Transformer (RRF)", "hybrid_reranker":"Hybrid + Cross-Encoder"}
    for name, result in retrieval.items():
        status = result.get("metadata", {}).get("status", "NOT RUN")
        metrics = result.get("metrics", {})
        latency = result.get("latency_ms", {}).get("mean")
        lines.append(f"| {labels[name]} | {status} | {value(metrics, 'hit_at_1')} | {value(metrics, 'recall_at_3')} | {value(metrics, 'mrr')} | {'—' if latency is None else f'{latency:.2f} ms'} |")
    lines.extend([
        "", "Dense LSA is a reproducible TF-IDF + truncated-SVD baseline and is not a pretrained neural model. Pretrained MiniLM and Cross-Encoder results use locally downloaded public model artifacts.", "",
        "## Evidence-gate ablation", "", "| Arm | Target-paper coverage | Refusal accuracy |", "|---|---:|---:|",
    ])
    if gate_off and gate_on:
        lines.extend([f"| Gate OFF | {gate_off['target_paper_coverage']:.3f} | {gate_off['refusal_accuracy']:.3f} |", f"| Gate ON | {gate_on['target_paper_coverage']:.3f} | {gate_on['refusal_accuracy']:.3f} |"])
    else:
        lines.append("| NOT RUN | — | — |")
    lines.extend([
        "", "This deterministic gate only handles exact-detail questions with missing named constraints. Answer correctness remains NOT RUN because no independent semantic labels exist.", "",
        "## Citation and reliability", "",
        f"- Exact-quote provenance: {citation['claims'] if citation else 0} returned claims; structural grounded rate {citation['evidence_grounded_rate_structural']:.3f}. Semantic entailment: NOT RUN." if citation else "- Citation evaluation: REQUIRES DATA.",
        f"- Fault injection: {reliability['recovered']}/{reliability['cases']} scenarios recovered ({reliability['recovery_success_rate']:.1%})." if reliability else "- Reliability evaluation: NOT RUN.",
        f"- Extractive benchmark performance: {performance['runs']} runs, mean end-to-end latency {performance['average_latency_ms']:.2f} ms, failure rate {performance['failure_rate']:.1%}; API cost unavailable because no LLM calls were made." if performance and performance.get("average_latency_ms") is not None else "- Performance export: NOT RUN.",
        "- Verifier ablation and multi-agent versus simplified pipeline: REQUIRES API KEY; historical runs are not silently reused as new results.", "",
        "## Metric definitions", "",
        "- **Hit@K:** fraction of questions with at least one relevant item in the first K results.",
        "- **Recall@K:** fraction of all labeled relevant items recovered in the first K results, averaged across questions.",
        "- **MRR:** mean reciprocal rank of the first relevant item.",
        "- **nDCG@K:** rank-discounted relevance normalized by an ideal ordering.",
        "- Paper-level metrics deduplicate chunks by paper ID. Chunk-level metrics require explicit chunk labels and are not reported for the current benchmark.", "",
        "## Reproduction", "", "```powershell", "python scripts/validate_benchmark.py", "python scripts/run_benchmark.py --profile full", "```", "",
    ])
    docs = ROOT / "docs"; docs.mkdir(exist_ok=True)
    (docs / "BENCHMARK.md").write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps({"status": "generated", "path": "docs/BENCHMARK.md"}))


if __name__ == "__main__":
    main()
